---
format_version: 10
pipelines:
  node-microservice:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/MartinsGrinfelds/ci_course.git
        branch: main
    stages:
      - build:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Building node application..."
      - deploy-dev:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Deployment on DEV environment triggered..."
      - test-dev:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Running tests on DEV environment triggered..."
      - deploy-int:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Deployment on INT environment triggered..."
      - test-int:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Running tests on INT environment triggered..."
      - deploy-prd:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Deployment on PRD environment triggered..."
      - test-prd:
          jobs:
            build:
              tasks:
              - exec:
                  command: bash
                  arguments:
                    -  -c
                    -  echo "Running tests on PRD environment triggered..."