---
format_version: 10
common:
  deploy-task: &deploy-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Deployment on ${ENV_NAME} environment triggered..."
          #build job: "ui-tests", parameters: [string(name: "ENVIRONMENT", value: "${environment}")]
  test-task: &test-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Running tests on ${ENV_NAME} environment triggered..."
        command: bash
        arguments:
          -  -c
          -  docker run --network=host -d -t --name api_test_executor_${ENV_NAME} api_test_executor
        command: bash
        arguments:
          -  -c
          -  docker exec api_test_executor_${ENV_NAME} cucumber --tags=@${ENV_NAME} --format html --out test-output/report.html
        command: bash
        arguments:
          -  -c
          -  docker cp api_test_executor_${ENV_NAME}:/usr/src/api-tests/test-output/report.html report_${ENV_NAME}.html
        command: bash
        arguments:
          -  -c
          -  docker rm -f api_test_executor_${ENV_NAME}
pipelines:
  node-microservice:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/MartinsGrinfelds/ci_course.git
        branch: main
    stages:
      - build:
            deploy:
              tasks:
                *deploy-tasks
      - deploy-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks:
                *test-tasks
      - deploy-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks:
                *test-tasks
      - deploy-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks:
                *test-tasks