---
format_version: 10
common:
  deploy-task: &deploy-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Deployment on ${ENV_NAME} environment triggered..."
  test-task: &test-tasks
    - exec:
        command: bash
        arguments:
          -  -c
          -  echo "Running tests on ${ENV_NAME} environment triggered..."

pipelines:
  node-microservice:
    group: microservices
    materials:
      mainGit:
        git: https://github.com/MartinsGrinfelds/ci_course.git
        branch: main
    stages:
      - build:
            deploy:
              tasks:
                *deploy-tasks
      - deploy-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-dev:
          environment_variables:
            ENV_NAME: DEV
          jobs:
            deploy:
              tasks:
                *test-tasks
      - deploy-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-int:
          environment_variables:
            ENV_NAME: INT
          jobs:
            deploy:
              tasks:
                *test-tasks
      - deploy-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks:
                *deploy-tasks
      - test-prd:
          environment_variables:
            ENV_NAME: PRD
          jobs:
            deploy:
              tasks:
                *test-tasks